### ISSUE TITLE
JSON outputter cannot handle CCG categories

### ISSUE THREAD

**Issue by hiroshinoji** [mynlp/jigg#41]
Example:

``` bash
$ java -cp "*" jigg.pipeline.Pipeline -annotators "ssplit,kuromoji,jaccg" -outputFormat json
Loading parser model in ccg-models/parser/beam=64.ser.gz ...done [5.2 sec]
> 東京は晴れです
Exception in thread "main" com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape 'N' (code 78)
 at [Source: {".tag":"root",".child":[{".tag":"document","id":"d0",".child":[{".tag":"sentences",".child":[{".tag":"sentence","text":"東京は晴れです","id":"s0","characterOffsetBegin":"0","characterOffsetEnd":"7",".child":[{".tag":"tokens","annotators":"kuromoji",".child":[{".tag":"token","id":"s0_0","form":"東京","characterOffsetBegin":"0","characterOffsetEnd":"2","pos":"名詞","pos1":"固有名詞","pos2":"地域","pos3":"一般","cType":"*","cForm":"*","lemma":"東京","yomi":"トウキョウ","pron":"トーキョー"},{".tag":"token","id":"s0_1","form":"は","characterOffsetBegin":"2","characterOffsetEnd":"3","pos":"助詞","pos1":"係助詞","pos2":"*","pos3":"*","cType":"*","cForm":"*","lemma":"は","yomi":"ハ","pron":"ワ"},{".tag":"token","id":"s0_2","form":"晴れ","characterOffsetBegin":"3","characterOffsetEnd":"5","pos":"名詞","pos1":"一般","pos2":"*","pos3":"*","cType":"*","cForm":"*","lemma":"晴れ","yomi":"ハレ","pron":"ハレ"},{".tag":"token","id":"s0_3","form":"です","characterOffsetBegin":"5","characterOffsetEnd":"7","pos":"助動詞","pos1":"*","pos2":"*","pos3":"*","cType":"特殊・デス","cForm":"基本形","lemma":"です","yomi":"デス","pron":"デス"}]},{".tag":"ccg","annotators":"jaccg","root":"s0_sp0","id":"s0_ccg0","score":"319.1745958328247",".child":[{".tag":"span","id":"s0_sp0","begin":"0","end":"4","symbol":"S[mod=nm,form=base,fin=f]","rule":"&gt;","children":"s0_sp1 s0_sp4"},{".tag":"span","id":"s0_sp1","begin":"0","end":"2","symbol":"S[fin=f]/S[fin=f]","rule":"&lt;","children":"s0_sp2 s0_sp3"},{".tag":"span","id":"s0_sp2","begin":"0","end":"1","symbol":"NP[mod=nm,case=nc,fin=f]","children":"s0_0"},{".tag":"span","id":"s0_sp3","begin":"1","end":"2","symbol":"(S[fin=f]/S[fin=f])\NP[mod=nm,case=nc,fin=f]","children":"s0_1"},{".tag":"span","id":"s0_sp4","begin":"2","end":"4","symbol":"S[mod=nm,form=base,fin=f]","rule":"&lt;","children":"s0_sp5 s0_sp6"},{".tag":"span","id":"s0_sp5","begin":"2","end":"3","symbol":"NP[mod=nm,case=nc,fin=f]","children":"s0_2"},{".tag":"span","id":"s0_sp6","begin":"3","end":"4","symbol":"S[mod=nm,form=base,fin=f]\NP[mod=nm,case=nc,fin=f]","children":"s0_3"}]}]}]}]}]}; line: 1, column: 1609]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._handleUnrecognizedCharacterEscape(ParserMinimalBase.java:510)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._decodeEscaped(ReaderBasedJsonParser.java:2208)
        ...
```

The problem seems in escaping backslash `\` in CCG categories like N\N.

**Comment by kyoshinaga** [comment]
Sorry for the inconvenience. And thanks for your notification.
This problem seems to be related with a parsing method of `Jackson`.
I'll modify it soon.

**Comment by kyoshinaga** [comment]
I modified this bug with escaping a backslash `\` to `\\`.

Example: 

``` bash
$ echo "東京は雨です。" | java -cp "./target/*" jigg.pipeline.Pipeline -annotators "ssplit,kuromoji,jaccg" -outputFormat json
Loading parser model in ccg-models/parser/beam=64.ser.gz ...done [4.0 sec]
{
  ".tag" : "root",
  ".child" : [ {
...
          }, {
            ".tag" : "span",
            "id" : "s0_sp7",
            "begin" : "3",
            "end" : "4",
            "symbol" : "S[mod=nm,form=base,fin=f]\\NP[mod=nm,case=nc,fin=f]",
            "children" : "s0_3"
          }, {
...
}
```
