### ISSUE TITLE
xml output error when using PipeLine server

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#56]
Trying to run a simple curl request, and output xml. The below runs fine when using json.
```
$ curl -s --data 'this is my first.' "http://localhost:8080/annotate?outputFormat=xml&annotators=corenlp%5Btokenize%2Cssplit%5D"
```

The server logs show the below...
``` 
Server online at localhost:8080/
Press RETURN to stop...
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Volumes/disk/InvestmentPlanning/Development/test/textPipeline/components/textPreProcessor/jigg/target/jigg-0.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Volumes/disk/InvestmentPlanning/Development/test/textPipeline/components/textPreProcessor/jigg/target/jigg-assembly-0.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Volumes/disk/InvestmentPlanning/Development/test/textPipeline/components/textPreProcessor/jigg/target/jigg-assembly-server-0.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[jigg-server-akka.actor.default-dispatcher-8] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[jigg-server-akka.actor.default-dispatcher-8] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
[jigg-server-akka.actor.default-dispatcher-8] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
Uncaught error from thread [jigg-server-akka.actor.default-dispatcher-8] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[jigg-server]
java.lang.NoSuchMethodError: jigg.pipeline.Pipeline.writeTo(Ljava/io/Writer;Lscala/xml/Node;)V
	at jigg.pipeline.PipelineServer$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.outputBy$1(PipelineServer.scala:140)
	at jigg.pipeline.PipelineServer$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PipelineServer.scala:144)
	at jigg.pipeline.PipelineServer$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$2.apply(PipelineServer.scala:134)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by hiroshinoji** [comment]
@JSB97 The error message seems to say that there are multiple assembled jar files in the current path.

Try removing `target/jigg-0.6.2.jar` and `target/jigg-asembly-server-0.6.2.jar` and running again? Also the escape problem is solved in the latest version. See https://github.com/mynlp/jigg/issues/50#issuecomment-280557768.

**Comment by JSB97** [comment]
Apolgies - yes there is an explanation in the error log;
> http://www.slf4j.org/codes.html#multiple_bindings

Thank you
