### ISSUE TITLE
Server does not return annotations

### ISSUE THREAD

**Issue by JSB97** [mynlp/jigg#69]
I am processing text data, and for about 5~10% of cases jigg fails to return the expected results.
The JIGG internal errors dont give to many clues as to the underlying cause, but any ideas?

```
# curl command
curl --data-urlencode 'annotators=ssplit,mecab,cabocha' --data-urlencode 'q=特集——福田氏?小沢氏?日本の顔、次の衆院選、政治の岐路「福田色」腐心 ねじれ国会、なお壁に 二〇〇八年は日本の政治にとって大きな岐路になる。年内に次期衆院選が実施されるとの観測が強いためだ。福田政権を継続させるのか、小沢一郎代表が率いる最大野党、民主党に政権を担わせるのか、それとも「第三の道」を選ぶのか。有権者の一票が日本の進路に大きな重みを持つ。 首相は今年前半に外交で「福田カラー」を出し、年後半から社会保障などの難題に取り組むシナリオを描く。この中で一番、実績をアピールできるタイミングを選び、解散・総選挙に打って出る構えだ。 首相が外交の看板に掲げるのが、良好な日米関係を足場にアジア各国との連携を強める「共鳴外交」。日米同盟の堅持と対中関係などの強化を両立させる路線だ。「対米追随外交」をやり玉に挙げる小沢氏の批判をかわしつつ、独自色を出す狙いだ。 福田外交にとっての大きなヤマ場は七月の主要国首脳会議だ。首相は地ならしを進めるため、五月の大型連休に欧州の主要国を歴訪する方向。サミット参加国の首脳陣と顔見知りになり、議長として指導力を発揮しやすくするためだ。 サミットの主要議題となる地球温暖化対策では、米中など温暖化ガスの主要排出国との協力がカギを握る。今春に来日する予定の胡錦濤中国国家主席にも協力を要請する腹づもりだ。 年後半には次期衆院選の大きな争点になる内政の課題も待ったなしだ。特に大きいのが、消費税問題。二〇〇九年度には基礎年金国庫負担割合の引き上げが控える。首相はその財源を確保するため、年末の〇九年度税制改正大綱に向けて消費税率引き上げ論議に取り組む意向だ。 首相は秋以降の展開をにらみ、すでに一つの仕掛けを施している。社会保障制度の将来像を描く国民会議の創設がそれだ。政党代表だけでなく、経済界や労働界、有識者らもメンバーに加えることで、給付と負担のあり方に関する国民の合意形成につなげる狙いだ。 社会保障論議と並行して「成長力の強化」にも力を入れる方針だ。増税論議に偏らない姿勢を強調し、税率の引き上げ幅をできるだけ圧縮する努力を示すことで、国民の理解を得る思惑がのぞく。 首相は次期衆院選でこれらの政策を訴えるとみられるが、過半数の議席を確保できたとしても、どこまで公約を実現できるかは不透明だ。参院で与野党が逆転する「ねじれ国会」の構図は変わらないからだ。 現在、与党は参院で否決された法案を衆院で再議決・可決するのに必要な三分の二の議席を握るが、この勢力も維持は困難との見方が多い。有権者はこうした事情も考慮に入れ、一票を投じる必要がある。' 'http://localhost:8080/annotate?outputFormat=json'
```

```
# Jigg internal error
[ERROR] [07/26/2017 12:51:50.741] [jigg-server-akka.actor.default-dispatcher-16] [akka.actor.ActorSystemImpl(jigg-server)] Error during processing of request: 'java.lang.AssertionError: assertion failed
    at scala.Predef$.assert(Predef.scala:156)
    at jigg.pipeline.AnnotatingInParallel$class.divideBy(AnnotatingInParallel.scala:74)
    at jigg.pipeline.AnnotatingInParallel$class.annotateInParallel(AnnotatingInParallel.scala:54)
    at jigg.pipeline.MecabAnnotator.annotateInParallel(MecabAnnotator.scala:27)
    at jigg.pipeline.AnnotatingSentencesInParallel$$anonfun$annotate$1.apply(AnnotatingInParallel.scala:95)
    at jigg.pipeline.AnnotatingSentencesInParallel$$anonfun$annotate$1.apply(AnnotatingInParallel.scala:93)
    at jigg.util.XMLUtil$RichNode.jigg$util$XMLUtil$RichNode$$recurse$2(XMLUtil.scala:93)
    at jigg.util.XMLUtil$RichNode$$anonfun$3.apply(XMLUtil.scala:94)
    at jigg.util.XMLUtil$RichNode$$anonfun$3.apply(XMLUtil.scala:94)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at jigg.util.XMLUtil$RichNode.jigg$util$XMLUtil$RichNode$$recurse$2(XMLUtil.scala:94)
    at jigg.util.XMLUtil$RichNode$$anonfun$3.apply(XMLUtil.scala:94)
    at jigg.util.XMLUtil$RichNode$$anonfun$3.apply(XMLUtil.scala:94)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at jigg.util.XMLUtil$RichNode.jigg$util$XMLUtil$RichNode$$recurse$2(XMLUtil.scala:94)
    at jigg.util.XMLUtil$RichNode.replaceAll(XMLUtil.scala:97)
    at jigg.pipeline.AnnotatingSentencesInParallel$class.annotate(AnnotatingInParallel.scala:93)
    at jigg.pipeline.MecabAnnotator.annotate(MecabAnnotator.scala:27)
    at jigg.pipeline.Pipeline.annotateRecur$1(Pipeline.scala:351)
    at jigg.pipeline.Pipeline.annotate(Pipeline.scala:360)
    at jigg.pipeline.Pipeline$$anonfun$annotateText$1.apply(Pipeline.scala:341)
    at jigg.pipeline.Pipeline$$anonfun$annotateText$1.apply(Pipeline.scala:339)
    at jigg.pipeline.Pipeline.process(Pipeline.scala:327)
    at jigg.pipeline.Pipeline.annotateText(Pipeline.scala:339)
    at jigg.pipeline.Pipeline.annotate(Pipeline.scala:344)
    at jigg.pipeline.PipelineServer$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$4.apply(PipelineServer.scala:159)
    at jigg.pipeline.PipelineServer$$anonfun$1$$anonfun$apply$1$$anonfun$apply$2$$anonfun$apply$3$$anonfun$4.apply(PipelineServer.scala:157)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
'. Completing with 500 Internal Server Error response.
```

**Comment by hiroshinoji** [comment]
Sorry this was definitely a bug in the recent updates on parallel processing. I think now it is fixed in the develop branch (so manual build is required).

Recently, I updated `build.sbt` so that the server can be launched on `sbt` without compiling, which takes too much time. Try the following, which is much faster than `assembly`:

```bash
$ bin/sbt # launch sbt
> runMain jigg.pipeline.PipelineServer
```

Then you can call the server as usual.

**Comment by hiroshinoji** [comment]
This was due to a bug, and now the fix is already incorporated in the current master.
